// Code generated by "stringer -linecomment -type TypeMode"; DO NOT EDIT.

package pdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeModeNone-0]
	_ = x[TypeModePointer16-256]
	_ = x[TypeModePointer16Far-512]
	_ = x[TypeModePointer16Huge-768]
	_ = x[TypeModePointer32-1024]
	_ = x[TypeModePointer32Far-1280]
	_ = x[TypeModePointer64-1536]
	_ = x[TypeModePointer128-1792]
}

const (
	_TypeMode_name_0 = "TypeMode(none)"
	_TypeMode_name_1 = "16 bit pointer"
	_TypeMode_name_2 = "16:16 far pointer pointer"
	_TypeMode_name_3 = "16:16 huge pointer pointer"
	_TypeMode_name_4 = "32 bit pointer"
	_TypeMode_name_5 = "16:32 far pointer"
	_TypeMode_name_6 = "64 bit pointer"
	_TypeMode_name_7 = "128 bit pointer"
)

func (i TypeMode) String() string {
	switch {
	case i == 0:
		return _TypeMode_name_0
	case i == 256:
		return _TypeMode_name_1
	case i == 512:
		return _TypeMode_name_2
	case i == 768:
		return _TypeMode_name_3
	case i == 1024:
		return _TypeMode_name_4
	case i == 1280:
		return _TypeMode_name_5
	case i == 1536:
		return _TypeMode_name_6
	case i == 1792:
		return _TypeMode_name_7
	default:
		return "TypeMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
