// Code generated by "stringer -linecomment -type TypeKind"; DO NOT EDIT.

package pdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeKindNone-0]
	_ = x[TypeKindAbs-1]
	_ = x[TypeKindSegment-2]
	_ = x[TypeKindVoid-3]
	_ = x[TypeKindHResult-8]
	_ = x[TypeKindCurrency-4]
	_ = x[TypeKindBasicStringNear-5]
	_ = x[TypeKindBasicStringFar-6]
	_ = x[TypeKindNotTranslated-7]
	_ = x[TypeKindBit-96]
	_ = x[TypeKindPascalChar-97]
	_ = x[TypeKindBool32FFFFFFFF-98]
	_ = x[TypeKindCharacter-112]
	_ = x[TypeKindWideCharacter-113]
	_ = x[TypeKindRune16-122]
	_ = x[TypeKindRune32-123]
	_ = x[TypeKindInt8-104]
	_ = x[TypeKindUint8-105]
	_ = x[TypeKindInt16-114]
	_ = x[TypeKindUint16-115]
	_ = x[TypeKindInt32-116]
	_ = x[TypeKindUint32-117]
	_ = x[TypeKindInt64-118]
	_ = x[TypeKindUint64-119]
	_ = x[TypeKindInt128-120]
	_ = x[TypeKindUint128-121]
	_ = x[TypeKindInt8Byte-16]
	_ = x[TypeKindUint8Byte-32]
	_ = x[TypeKindInt16Short-17]
	_ = x[TypeKindUint16Short-33]
	_ = x[TypeKindInt32Long-18]
	_ = x[TypeKindInt64Quad-19]
	_ = x[TypeKindUint64Quad-35]
	_ = x[TypeKindInt128Octet-20]
	_ = x[TypeKindUint128Octet-36]
	_ = x[TypeKindFloat16-70]
	_ = x[TypeKindFloat32-64]
	_ = x[TypeKindFloat32PP-69]
	_ = x[TypeKindFloat48-68]
	_ = x[TypeKindFloat64-65]
	_ = x[TypeKindFloat80-66]
	_ = x[TypeKindFloat128-67]
	_ = x[TypeKindComplex32-80]
	_ = x[TypeKindComplex64-81]
	_ = x[TypeKindComplex80-82]
	_ = x[TypeKindComplex128-83]
	_ = x[TypeKindBool8-48]
	_ = x[TypeKindBool16-49]
	_ = x[TypeKindBool32-50]
	_ = x[TypeKindBool64-51]
	_ = x[TypeKindBool128-52]
	_ = x[TypeKindInternal-240]
}

const _TypeKind_name = "uncharacterized type (no type)absolute symbolsegment typevoidBASIC 8 byte currency valuenear BASIC stringfar BASIC stringtype not translated by cvpackHRESULT8 bit signed16 bit signed32 bit signed64 bit signed128 bit signed8 bit unsigned16 bit unsigned64 bit unsigned128 bit unsigned8 bit boolean16 bit boolean32 bit boolean64 bit boolean128 bit boolean32 bit real64 bit real80 bit real128 bit real48 bit real32 bit partial-precision real16 bit real32 bit complex64 bit complex80 bit complex128 bit complexbitPascal CHAR32-bit BOOL where true is 0xffffffff8 bit signed int8 bit unsigned intreally a charwide char16 bit signed int16 bit unsigned int32 bit signed int32 bit unsigned int64 bit signed int64 bit unsigned int128 bit signed int128 bit unsigned int16-bit unicode char32-bit unicode charCV internal type"

var _TypeKind_map = map[TypeKind]string{
	0:   _TypeKind_name[0:30],
	1:   _TypeKind_name[30:45],
	2:   _TypeKind_name[45:57],
	3:   _TypeKind_name[57:61],
	4:   _TypeKind_name[61:88],
	5:   _TypeKind_name[88:105],
	6:   _TypeKind_name[105:121],
	7:   _TypeKind_name[121:150],
	8:   _TypeKind_name[150:157],
	16:  _TypeKind_name[157:169],
	17:  _TypeKind_name[169:182],
	18:  _TypeKind_name[182:195],
	19:  _TypeKind_name[195:208],
	20:  _TypeKind_name[208:222],
	32:  _TypeKind_name[222:236],
	33:  _TypeKind_name[236:251],
	35:  _TypeKind_name[251:266],
	36:  _TypeKind_name[266:282],
	48:  _TypeKind_name[282:295],
	49:  _TypeKind_name[295:309],
	50:  _TypeKind_name[309:323],
	51:  _TypeKind_name[323:337],
	52:  _TypeKind_name[337:352],
	64:  _TypeKind_name[352:363],
	65:  _TypeKind_name[363:374],
	66:  _TypeKind_name[374:385],
	67:  _TypeKind_name[385:397],
	68:  _TypeKind_name[397:408],
	69:  _TypeKind_name[408:437],
	70:  _TypeKind_name[437:448],
	80:  _TypeKind_name[448:462],
	81:  _TypeKind_name[462:476],
	82:  _TypeKind_name[476:490],
	83:  _TypeKind_name[490:505],
	96:  _TypeKind_name[505:508],
	97:  _TypeKind_name[508:519],
	98:  _TypeKind_name[519:555],
	104: _TypeKind_name[555:571],
	105: _TypeKind_name[571:589],
	112: _TypeKind_name[589:602],
	113: _TypeKind_name[602:611],
	114: _TypeKind_name[611:628],
	115: _TypeKind_name[628:647],
	116: _TypeKind_name[647:664],
	117: _TypeKind_name[664:683],
	118: _TypeKind_name[683:700],
	119: _TypeKind_name[700:719],
	120: _TypeKind_name[719:737],
	121: _TypeKind_name[737:757],
	122: _TypeKind_name[757:776],
	123: _TypeKind_name[776:795],
	240: _TypeKind_name[795:811],
}

func (i TypeKind) String() string {
	if str, ok := _TypeKind_map[i]; ok {
		return str
	}
	return "TypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
}
